services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      # The .env file takes precedence. If some variable is not set,
      # the .env.example file is used for the missing variables.
      - .env
      - .env.example
    volumes:
      - ./app:/code/app
      - ./tests:/code/tests
      - ./assets:/code/assets
    ports:
      - "8080:8080"
    command: uvicorn app.main:app --host=0.0.0.0 --port=8080 --reload
    restart: on-failure
    networks:
      - eventito-dev-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - eventito-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  eventito-dev-network:
    name: eventito-dev-network
    external: true
