services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      # The .env file takes precedence. If some variable is not set,
      # the .env.example file is used for the missing variables.
      - .env
      - .env.example
    volumes:
      - .:/code
    ports:
      - "5678:5678"  # Debug port
    command: uvicorn app.main:app --host=0.0.0.0 --port=8080 --reload
    networks:
      - eventito-dev-network
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - eventito-dev-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway:
    image: gateway:latest
    build:
      context: ../gateway
      dockerfile: Dockerfile
    environment:
      - PORT=12345
      - BACKEND_URL=http://backend:8080
      - FIREBASE_KEY=${FIREBASE_KEY}
    volumes:
      - ../gateway:/usr/src/app
    ports:
      - "12346:12345"
    working_dir: /usr/src/app
    networks:
      - eventito-dev-network
  client:
    build:
      context: ../frontend
      dockerfile: development.dockerfile
    image: client:dev
    command: npm run dev -- --host
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - eventito-dev-network
networks:
  eventito-dev-network:
    name: eventito-dev-network
    external: true
