name: Tests

on:
  push:
    branches: [ develop, main ]
  pull_request: 
    branches: [ develop, main ]
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test python API
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: .
    env:
    # Database
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/
    # Storage 
      EVENTS_BUCKET: events-bucket
      WORKS_BUCKET: works-bucket
      CERTIFICATES_BUCKET: certificates-bucket
      USERS_BUCKET: users-bucket
      PUBLIC_BASE_URL: https://storage.googleapis.com/
      TYPE_STORAGE: NO_STORAGE
    # Notifications
      NOTIFICATIONS_EMAIL: ''
      NOTIFICATIONS_EMAIL_PASSWORD: ''
      NOTIFICATIONS_FRONTEND_URL: https://eventito-frontend.vercel.app/
      NOTIFICATIONS_ENABLE_SEND_EMAILS: False

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements-dev.txt
    - name: Run tests and collect coverage
      run: python3 -m pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov for main
      if: github.ref == 'refs/heads/main'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
