name: Tests

on:
  push:
    branches: [ develop, main ]
  pull_request: 
    branches: [ develop, main ]
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: Test python API
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    defaults:
      run:
        working-directory: .
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install requirements
      run: pip install -r requirements-dev.txt

    - name: Install dotenv CLI
      run: pip install python-dotenv

    - name: Load environment variables from .env_example
      run: |
        # Export environment variables from .env_example
        set -o allexport
        source .env_example
        set +o allexport

    - name: Run tests and collect coverage
      run: python3 -m pytest --cov=./ --cov-report=xml
    - name: Upload coverage reports to Codecov for main
      if: github.ref == 'refs/heads/main'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
